### PR TITLE
Feature/return uploaded keys

### LINKED ISSUE #2: feature request:- return s3 urls after upload
Hey,

I'd like to be able to return the uploaded paths via the API, so that I can use the artefact URL's in a future step.

I have a slack-reporter for Cypress, that I would like to upload the artefacts to S3 and use the returned URL's in the slack message, to provide a link to the slack artefacts.

Many thanks for the great project!

### PR DESCRIPTION
**Pull request by ThaNarie**
closes #2 

Returns the uploaded file locations (relative to the bucket) of the uploaded file(s). With this, you can append your own S3 url settings to link to the files.

@YOU54F I've tried to implement your feature request here, please let me know if this works for you the way it's doen!

### CODE REVIEW

**Comment by YOU54F** [comment]
Thanks @ThaNarie, I will grab my laptop and test it out shortly.

I was tearing my hair out trying to do it directly with the sdk, so really appreciate you helping me out on this one. I’m a novice programmer so great to be led by example 🤙

**Comment by YOU54F** [comment]
@ThaNarie 

Absolutely spot on fella!!! Thank you so much for the work on this!!!


```
2019-06-09T19:32:01.068Z - info: results 
{ s3PathsVideos: [ 'cypress/videos/small.mp4' ] }
2019-06-09T19:32:01.072Z - info: results 
{ s3PathsScreenshots: {} }
2019-06-09T19:32:01.072Z - info: results 
{ s3PathsReports:
   [ 'mochareports/assets/MaterialIcons-Regular.woff',
     'mochareports/assets/roboto-light-webfont.woff2',
     'mochareports/assets/app.css',
     'mochareports/assets/roboto-light-webfont.woff',
     'mochareports/assets/app.js',
     'mochareports/assets/roboto-medium-webfont.woff',
     'mochareports/assets/roboto-medium-webfont.woff2',
     'mochareports/assets/roboto-regular-webfont.woff',
     'mochareports/assets/MaterialIcons-Regular.woff2',
     'mochareports/assets/roboto-regular-webfont.woff2',
     'mochareports/report-20190605-211147.html',
     'mochareports/report-20190605-211144.json' ] }
```

**Comment by ThaNarie** [comment]
Glad to hear @YOU54F, the updated package is now also available on NPM for you to use

**Comment by YOU54F** [comment]
Thanks buddy! Enjoy the rest of your weekend, and thanks again for the project/work 👍 

If you even find yourself in Leeds in the UK, hit me up for a beer =D

**Pull request merged**
